# Generated by Django 4.1 on 2022-08-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_time',
            new_name='uploaded_date',
        ),
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
