# Generated by Django 4.0.6 on 2022-08-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='allowed_users',
            field=models.CharField(max_length=255),
        ),
    ]
