# Generated by Django 4.0.6 on 2022-08-15 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0006_alter_document_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='allowed_users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
